Visual Identity 1.0
fga-eps-mds/EPS-2020-2-G3 pull request #42
Opened 2021-02-26 17:51 UTC by SFernandoS

First version of the Visual Identity document

Authors: Fernando Vargas; and
Lais Aguiar.

2021-02-26 18:47 UTC, andrelucax commented
Favor seguir o template de PRs e adicionar o tópico de tarefas realizadas @SFernandoS

2021-02-26 18:51 UTC, andrelucax commented
Vamos evitar também utilizar muitos elementos HTML nesses documentos, existem opções em MD que resolvem.

2021-02-26 18:52 UTC, andrelucax commented on docs/product/visual-identity.md
> +<br></br>
remover elementos html desnecessarios.

2021-02-26 18:59 UTC, andrelucax commented on docs/product/visual-identity.md
> +<br></br>
Remover HTML desnecessario

2021-02-26 19:01 UTC, andrelucax commented on docs/product/visual-identity.md
> +<p>Para realizar  a definição das cores, o maior critério foi em algo relacionado a Identidade do Povo Kokama. Após analisarmos, chegamos ao consenso de que devemos tentar ao máximo destacar o vermel
Rever texto explicativo. Deixar mais claro e evitar uso de palavras genéricas (como 'algo')

2021-02-26 19:03 UTC, andrelucax commented on docs/product/visual-identity.md
> +## 2.2 Identidade das funcionalidades pelas cores
Tópico sem sentido para aplicação

2021-02-26 19:06 UTC, andrelucax commented on docs/product/visual-identity.md
> +<p>A tipografia utilizada na produção do aplicativo será a tipografia padrão para Android do Native Base. A tipografia será dividida em Tipografia da Identidade do Produto e a tipografia utilizada no
Fonte muito exagerada.

2021-02-26 19:07 UTC, andrelucax requested changes
Resolver pendencias citadas

2021-02-26 19:11 UTC, andrelucax commented
Lembrar de colocar assigne, labels e milestones tambem em futuros PRs

2021-02-26 19:34 UTC, SFernandoS commented on docs/product/visual-identity.md
> +<p>Para realizar  a definição das cores, o maior critério foi em algo relacionado a Identidade do Povo Kokama. Após analisarmos, chegamos ao consenso de que devemos tentar ao máximo destacar o vermel
A professora frisou muito sobre a cor vermelha, falou que era algo relacionada a uma árvore muito importante para o Povo Kokama, mas não aprofundou no assunto. Não sei nem o nome da árvore e não achei material na internet. Assim que possível, vou pedir um pouco mais de detalhes.

2021-02-26 19:35 UTC, SFernandoS commented on docs/product/visual-identity.md
> +## 2.2 Identidade das funcionalidades pelas cores
Apaguei o tópico

2021-02-26 19:36 UTC, SFernandoS commented on docs/product/visual-identity.md
> +<p>A tipografia utilizada na produção do aplicativo será a tipografia padrão para Android do Native Base. A tipografia será dividida em Tipografia da Identidade do Produto e a tipografia utilizada no
ok

2021-02-28 01:36 UTC, andrelucax commented on docs/product/visual-identity.md
> +<p> O documento de Identidade visual tem como principal objetivo definir os parâmetros dos objetos de design das telas da aplicação, que são:
HTML continua desnecessário, existem outras opções que podemos utilizar em MD. Não há necessidade dos <p> para novas linguas/paragrafos, podemos utilizar apenas quebra de linha e o MD entende. a lista utilizada pode ser resolvida com MD tambem.

ex:

# 1 Introducao

O documento de iden..

* ponto 1

* ponto 2

* ponto 3

2021-02-28 11:15 UTC, andrelucax commented
@SFernandoS @laispa percebi agora que o nome da branch não está correto. Olhar guia de contribuiçao depois

2021-02-28 13:21 UTC, andrelucax approved these changes
Fiz as mudanças necessárias e mudei alguns elementos, vou solicitar review de outra pessoa

2021-02-28 13:21 UTC, andrelucax commented on docs/product/visual-identity.md
> +
Adicionar o icone, podemos usar o icone que o nosso colega Lieverton montou pra gente, caso no final não seja o icone que iremos utilizar podemos atualizar o documento

2021-02-28 13:21 UTC, andrelucax commented on docs/product/visual-identity.md
> +<img src="https://github.com/fga-eps-mds/EPS-2020-2-G3/blob/visual-identity/docs/product/images/palette.png" alt="gradient" width= 450 height=200>
imagens em MD podem ser adicionads com ! [] () **SEM OS ESPACOS** , dentro dos brackets o nome da imagem e dentro do parenteses o link

2021-02-28 13:21 UTC, andrelucax commented on docs/product/visual-identity.md
> -TODO
Adicionar o tópico de Histórico de revisão

2021-03-01 22:21 UTC, leomedeiros1 commented
Me parece muito bom! Como solicitado, vou deixar o PR aberto.

2021-03-01 22:24 UTC, leomedeiros1 approved these changes
Me parece muito bom, tem minha aprovação! Como solicitado, vou manter o PR aberto.

2021-03-05 14:49 UTC, WelisonR commented
Após a reunião de hoje em que a professora escolher a logo e validar as cores utilizadas no protótipo, farei a aprovação.

Muito bom, pessoal!

2021-03-07 00:27 UTC, merged