34 documento visao
fga-eps-mds/EPS-2020-2-G3 pull request #44
Opened 2021-02-26 21:01 UTC by aluzianobriceno

## Descrição 

## Tarefas realizadas

2021-02-27 14:25 UTC, lievertom commented
É necessário completar as informações do PR, como a descrição, tarefas realizadas e os revisores. Por favor adicionar as informações. Se tiverem dúvidas podemos reunir no canal do *discord* para preencher as informações.

2021-02-27 22:51 UTC, WelisonR commented on docs/project/vision-document.md
> +Esse documento de visão tem como objetivo mostrar todos os paramentros do projeto Kokama, definir todas as funcionaliades do aplicativo que será desenvolvido, explicar de uma maneira clara e precisa
mostras todos os parâmetros -> apresentar o escopo e o propósito
funcionaliades -> funcionalidades

2021-02-27 22:51 UTC, WelisonR commented on docs/project/vision-document.md
> +Esse documento de visão tem como objetivo mostrar todos os paramentros do projeto Kokama, definir todas as funcionaliades do aplicativo que será desenvolvido, explicar de uma maneira clara e precisa
mostras todos os parâmetros -> apresentar o escopo e o propósito
funcionaliades -> funcionalidades

2021-02-27 22:57 UTC, WelisonR commented on docs/project/vision-document.md
> +* Webapp - Aplicação desenvolvido para simular um aplicativo, porém de forma a comportar-se como uma página web.
Remover acrônimos não utilizados no texto

2021-02-27 23:04 UTC, WelisonR commented on docs/project/vision-document.md
> +Os povos indígenas, através dos anos, vem sofrendo com o descaso da sociedade para com eles, tendo como consequências a perda de suas culturas. O povo Kokama não seria diferente, nessa pandemia eles
cerca 90* anciões -> cerca de 90 anciões
isso significa uma perda significativa -> isso significa uma perda considerável

2021-02-27 23:09 UTC, WelisonR commented on docs/project/vision-document.md
> +Para a professora Altaci quem viu  a necessidade de armazenar e disseminar o conhecimento da sua cultura, esse aplicativo fornece bem mais que uma ajuda, mas sana uma necessidade de seu povo. O tradu
Vírgula após Altaci
portugues -> português
esperado pela professora Altaci -> esperado pelos estudantes, professores e demais interessados na cultura kokama

2021-02-27 23:10 UTC, WelisonR commented on docs/project/vision-document.md
> +| Grupo                     | Descrição                             | Responsabilidade             |
Adicionar EPS, professor a parte interessada

2021-02-27 23:12 UTC, WelisonR commented on docs/project/vision-document.md
> +O Projeto Kokama é um aplicativo mobile, com o intuito de ajudar os Kokamas, alunos, professores e entusiastas dessa cultura a traduzir palavras, facilitar o ensinamento desse idioma e ensinar um pou
aplicativo mobile -> aplicativo mobile multiplataforma
e atividades,S -> e atividade, além de mostrar a história e cultura do povo Kokama

2021-02-27 23:14 UTC, WelisonR commented on docs/project/vision-document.md
> +O aplicativo Projeto Kokama, será disponibilizado por meio da Play Store, contando com uma instalação simples e intuitiva, melhorando a experiência do usuário.**
Play Store e Apple Store

2021-02-27 23:15 UTC, WelisonR commented on docs/project/vision-document.md
> +É a principal função do aplicativo, o usuário entra com uma palavra em português e recebe a respectiva palavra em Kokama e vice-versa
Descrever outras funcionalidades importantes relacionadas a tradução: ditos femininos e masculinos, frases de exemplo da palavra Kokama

2021-02-27 23:16 UTC, WelisonR commented on docs/project/vision-document.md
> +O aplicativo deve fazer referência as cores utilizadas no app anterior. A logo anterior deve ser preservada o máximo possível.
Descrever a importância de preservar as cores também

2021-02-27 23:18 UTC, WelisonR commented on docs/project/vision-document.md
> +O sistema deve ser resistente a invasões.
Complementar, pois o sistema não deve permitir pessoas não autorizadas a mudar significados e informações de traduções, visto que é um patrimônio cultural do povo

2021-02-27 23:19 UTC, WelisonR commented on docs/project/vision-document.md
> +Para o cadastro de novas palavras e atividades é necessário que o usuário tenha um cadastro no aplicativo. Entretanto, se o usuário apenas deseja utilizar o tradutor sem cadastrar nada não é necessár
Cadastro de palavras -> administrador do sistema
Usuário comum poderá ter login na aplicação

2021-02-27 23:21 UTC, WelisonR commented on docs/project/vision-document.md
> + ### __Resumo do Usuário:__
Complementar com outras partes interessadas: professor, time de desenvolvimento (EPS e MDS)

2021-02-27 23:26 UTC, WelisonR requested changes
Pessoal, parabéns pelo trabalho!! Verificar os pontos que destaquei nos comentários

2021-02-27 23:43 UTC, aluzianobriceno commented on docs/project/vision-document.md
> +| Grupo                     | Descrição                             | Responsabilidade             |
Acrescentei o professor e a equipe de EPS, quando a parte da comunidade Kokama, foi acrescentado um novo quadro falando dos usuários.

2021-02-28 00:14 UTC, WelisonR commented on docs/project/vision-document.md
> +Por conta da pandemia do covid-19 o povo Kokama, assim como o resto do mundo, tiveram muitas perdas entretanto, suas perdas são mais significativas já que estamos falando de um povo com uma população
Especificar melhor o escopo do projeto. Reescrever com foco nos seguintes itens: tradução, estudo e preservação da cultura do povo Kokama.

2021-02-28 00:18 UTC, WelisonR commented on docs/project/vision-document.md
> +O projeto inclui o primeiro aplicativo kokama tradutor desenvolvido pela Fira Soft, porém por motivos de negociação de direitos autorais a professora Altaci, que trabalha diretamente com esse povo in
Acredito que não seja necessário o parágrafo, não diz sobre as partes interessadas e sobre os usuários

2021-02-28 00:24 UTC, WelisonR commented on mkdocs.yml
> +      - Documentos:
Não é necessário um subtópico documentos, coloca, por favor, o documento de visão abaixo de "Projeto"

2021-02-28 02:00 UTC, merged